### PR TITLE
Allow any number of tank nodes; improve condensity entry and temp-based logic

### PR DESCRIPTION
**Pull request by spahrenk**
## Description
- Allows any number of tank nodes, which are no longer restricted to a multiple of 12. The values (which correspond to the node temperatures) are contained in std::vector<double> tankTemps_C.
- Allows any number of condensity-node values (> 0) to be entered in files or presets. The values are contained in a std::vector<double> condensity. This removes the need for resampling condensity. Simulation results are not affected by using a small, but equivalent, discrete representation of a distribution. Note that the logic in HeatSource::calcHeatDist appears to need improvement, but is not affected by these changes.
- The handling of TempBasedLogic nodes is somewhat improved, but the number of nodes remains fixed internally at LOGIC_NODE_SIZE (12). This size parameter was added to clarify the distinction between condensity and logic nodes, which was unclear in some places. Likewise, changing this value will result in test failure. 
- Changed internal container for heat sources to std::vector<HeatSource> heatSources.
- Included resampling functions (still in review) to convert among different container sizes.
- These changes and some stylistic edits were made toward converting to a schema-based system that admits novel HPWH models.
- Passes all tests.

## Author Progress Checklist:

- [X] Open draft pull request
    - [X] Make title clearly understandable in a standalone change log context
    - [X] Assign yourself the issue
    - [X] Add at least one label (enhancement, bug, or maintenance)
    - [ ] Link the issue(s) addressed by this PR (under "Development" in the sidebar menu) 
- [X] Make code changes (if you haven't already)
- [X] Self-review of code
    - [X] My code follows the style guidelines of this project
    - [X] I have added comments to my code, particularly in hard-to-understand areas
    - [X] I have only committed the necessary changes for this fix or feature
    - [X] I have made corresponding changes to the documentation
    - [X] My changes generate no new warnings
    - [X] I have ensured that my fix is effective or that my feature works as intended by:
        - [ ] exercising the code changes in the test framework, and/or
        - [X] manually verifying the changes (as explained in the the pull request description above)
    - [X] My changes pass all local tests
    - [X] My changes successfully passes CI checks
    - [X] Add any unit test for proof and documentation.
    - [X] Merge in main branch and address resulting conflicts and/or test failures.
- [X] Move pull request out of draft mode and assign reviewers
- [] Iterate with reviewers until all changes are approved
    - [ ] Make changes in response to reviewer comments
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
    - [ ] Re-request review in GitHub

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved

### CODE REVIEW

**Review by tanaya-mankad — COMMENTED** [review]
@spahrenk, something strange is happening with whitespace in your PRs - there are numerous places where the single space between a conditional and the opening parenthesis is removed, and that's the only change. It results in a lot of diffs that aren't relevant to technical changes.

**Comment by spahrenk** [comment]
I don't see any formatting specs for this project. I applied whatever the defaults are in VisualStudio., which look reasonable to me: no space after `if`. I doubt it is worth trying to recreate the original formatting, but if we are switching to the atheneum clang specs, I could go ahead and apply those and resubmit.

**Comment by tanaya-mankad** [comment]
I don't think we ever talked about this specifically, but a good goal for PRs is to only offer changes that are substantive - for example, not to change whitespace unless the whole PR is about formatting. If there's no formatting for the project, don't let VS apply one (this happened to me early on, in btwxt). It's just so reviewers aren't looking at changes that don't need review.
We'll merge the clang-format separately.

**Comment by spahrenk** [comment]
Of course. Too bad there isn't an option to ignore superficial changes in git.

**Comment by spahrenk** [comment]
While working on another issue, I found a few places where the number of nodes is still restricted. Will submit those changes soon.

**Comment by spahrenk** [comment]
I have removed the last vestiges of CONDENSITY_SIZE, except as a default value when instantiating resistance heat sources.

**Review by nealkruis — APPROVED** [review]
I think this is good, but there are so many formatting and other restructuring changes that it is hard to review the semantic changes here. I'm tempted to merge this, but in the future we should have separate PRs so it is easier to review.

**Pull request merged**
