### PR TITLE
Add clang format

### PR DESCRIPTION
**Pull request by tanaya-mankad**
Apply .clang-format to all source files; add CI task to check formatting upon push.

### CODE REVIEW

**Review by spahrenk — COMMENTED** [review]
We don't want BreakBeforeBraces: Stroustrup?

**Comment by tanaya-mankad** [comment]
> We don't want BreakBeforeBraces: Stroustrup?

Nope. Stroustrup won't line up the braces except for functions.

**Comment by spahrenk** [comment]
> > We don't want BreakBeforeBraces: Stroustrup?
> 
> Nope. Stroustrup won't line up the braces except for functions.

That's what I'm asking. You used Stroustrup in btwxt.

**Comment by tanaya-mankad** [comment]
Oh yeah,  thanks for the reminder. There are a lot of settings so it's entirely likely well miss some until we see them! InsertBraces is another one. I made the change in atheneum, so we'll propagate to everything soon.

**Review by spahrenk — APPROVED** [review]

**Comment by nealkruis** [comment]
What's going on with the failed checks?

**Comment by tanaya-mankad** [comment]
> What's going on with the failed checks?

Stupidity. I forgot to run the new clang-format before I checked it in!

**Pull request closed without merging**
